# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWxsZXJfZW1haWwiOiJxZXdAcXdlIiwic2VsbGVyX2lkIjoxLCJleHAiOjE3MDg4MDM4MDd9.eRvp7g9ptR9Hs6no5XKI8Hk5-wvANNXjUxE37-5HdDI

# Создаем продавца
POST http://localhost:8000/api/v1/seller/ HTTP/1.1
content-type: application/json

{
    "first_name": "Robert",
    "last_name": "Martin",
    "email": "qew@qwe",
    "password": "201307"
}


###

# Получаем токен продавца
POST http://localhost:8000/api/v1/token/ HTTP/1.1
content-type: application/json

{
    "email": "qew@qwe",
    "password": "201307"
}



###

# Получаем одного продавца по его ИД
GET http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

# Создаем книгу
POST http://localhost:8000/api/v1/books/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 104,
    "year": 2007,
    "seller_id": 2
}

###


# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем список продавцов
GET http://localhost:8000/api/v1/seller/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

###


# Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 10,
    "year": 2001,
    "id": 10,
    "seller_id": 3
}

###

# Обновляем поля в данных о продавце
PUT http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json

{
    "first_name": "Rot",
    "last_name": "Martin",
    "email": "qew@123.com",
    "id": 10
}

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/2 HTTP/1.1
content-type: application/json

###

# Удаляем продавца
DELETE http://localhost:8000/api/v1/seller/1 HTTP/1.1
content-type: application/json

###

# Удаляем продавца
POST http://localhost:8000/api/v1/token/ HTTP/1.1
content-type: application/json

{
    "email": "qew@qwe",
    "password": "201307"
}

###